### ISSUE TITLE
Redmine connection failed

### ISSUE THREAD

**Issue by suzukimitsuru** [emsk/redmine-notifier#1]
I have problem in  test connection.

- URL and API key inputed.
-  Redmine 2.3.4.stable

You have some information ?
Regards

**Comment by emsk** [comment]
Thank you for reporting.

I'm sorry, but Redmine Notifier 0.2.0 doesn't support Redmine < 2.5.0.

Redmine Notifier uses Issues API to get list of issues.
```
http://example.com/redmine/issues.json?updated_on=%3E%3D2016-01-02T08:12:32Z&sort=updated_on:desc
```

Redmine < 2.5.0, it doesn't accept timestamp format.
So, `2016-01-02T08:12:32Z` is invalid format in 2.3.4.stable.

Could you upgrade Redmine version to 2.5.0 or higher?
Or do you have any ideas to support < 2.5.0?

References:
* http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Listing-issues
* http://www.redmine.org/issues/8842
* http://www.redmine.org/projects/redmine/wiki/Changelog_2_5#250-2014-03-02
* http://blog.redmine.jp/articles/2_5/changelog/

**Comment by emsk** [comment]
Redmine Notifier 0.4.0 has been released!
It support Redmine version under 2.5.0.

https://github.com/emsk/redmine-notifier/releases/tag/v0.4.0

@suzukimitsuru Please try it.
